[package]
name = "genesis-generator"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
wasm-bindgen = "0.2.78"
regex = "1.5.4"
base64 = "0.13.0"
